### ISSUE TITLE
Control macro expansion in a query

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/cloogle.org#198] opened 2018-07-25 07:00 UTC
It would be nice to be able to control macro expansion in a query.
E.g. if you search for `:: a -> Pointer` you will get all functions returning an `Int` as well.
This is obviously correct since `:: Pointer :== Int` but I might only be interested in functions stating to deliver a `Pointer`.

**Comment by camilstaps** [comment] 2018-07-27 11:51
Essentially a duplicate of #145.

**Closed by camilstaps** 2018-07-27 11:51 UTC
Labels: enhancement
