### ISSUE TITLE
Strange search result order

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/cloogle.org#214] opened 2018-10-11 13:20 UTC
If I search for `enterinformation` I get a `G∀st` type first for some unknown reason:
https://cloogle.org/#enterinformation

![alt](https://martlubbers.net/scr/2018-10-11_15-21-19.png)

**Comment by camilstaps** [comment] 2018-10-11 13:48
This is probably due to incomplete resetting of the database in between cache reloads.

Every night, all requests in the cache are reloaded, and between these reloads, the database has to be reset because entries contain annotations that are used to order the results. This reset did not yet clear the annotations so the ordering got corrupted.

The issue does not appear on a fresh installation. I am creating a Platform MR to fix the database and will close this issue when the fix can be confirmed.

**Closed** 2018-10-12 10:04 UTC
Labels: backend, bug
